openapi: 3.0.0
info:
  title: AICS API
  description: The official torneo REST API
  version: 1.0.0

servers:
  - url: https://aics-api-a74878fb1caf.herokuapp.com/
    description: PROD server

paths:
  /api/v1/torneo/tournaments:
    get:
      summary: Get a list of tournaments
      tags:
        - Tournaments
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TournamentEntry'
        5XX:
          description: Server error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    TournamentEntry:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The ID of the tournament
        name:
          type: string
          description: The name of the tournament

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: FAILED
        data:
          type: object
          properties:
            error:
              type: string
              example: "Some error message"
